routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::post('favorites/sync', 'FavoritesController@sync');

Route::get('shopping-cart/content', 'ShoppingCartController@content');
Route::get('shopping-cart/subtotal', 'ShoppingCartController@subtotal');
Route::post('shopping-cart/update', 'ShoppingCartController@update');

/*
 *  Cart Item
 */

Route::group(['prefix' => 'cart-item'], function () {
    Route::get('item-by-id/{id}', 'CartItemController@item_by_id');
});

/**
 *  Order
 */

Route::group(['prefix' => 'order'], function(){
    Route::get('duplicate/{order}', 'AdminController@duplicate')->middleware('admin');
});

/*
 * POS
 */

Route::group(['prefix' => 'pos'], function () {
    Route::get('add-order-attended/{id}/{type}', 'PosController@add_order');
    Route::get('receipt/{order}', 'PosController@receipt');
});

/*
 *  Payment
 */

Route::group(['prefix' => 'payment'], function(){
    Route::post('in-store/{order}', 'PaymentsController@instore_payment')->name('pay-in-store');
});

Route::get('user/favorites', 'UserController@favorites');

Route::group(['prefix' => 'picking'], function () {
    Route::resource('item', 'ItemsController');

    Route::get('add-item/{order}/{upc}', 'PickingController@add_item')->name('add-item');
    Route::get('add-substitute/{order}/{old}/{new}', 'PickingController@add_substitute')->name('add-substitute');
    Route::get('order/{order}', 'PickingController@picking_items')->name('picking-order');
    Route::get('price-check', 'PickingController@price_check')->name('price-check');
    Route::get('substitute/{order}/{upc}', 'PickingController@substitute')->name('substitute');

    Route::post('item/is-out-of-stock/{id}', 'PickingController@is_out_of_stock')->name('is-out-of-stock');
    Route::post('picked/{order}', 'PickingController@picked');
});

Route::post('message/reply', 'NexmoController@reply');

Route::get('', 'ShoppingController@index')->name('home');

Route::get('lang/{lang}', 'LanguageController@language');

Route::get('delivery/update_delivery_status/{id}/{status}', 'DeliveryController@update_delivery_status');

Route::resource('category', 'CategoriesController');
Route::resource('department', 'DepartmentsController');

Route::post('order/cancel-order/{id}', 'OrdersController@cancel_order')->name('cancel-order');
Route::get('order/score/{order}/{score}', 'OrdersController@score_page')->name('order.score-page');
Route::post('order/score-comments/{order}', 'OrdersController@score_comments')->name('order.score-comments');

Route::resource('product', 'ProductsController');

Route::get('cart/payment/{order}/{status}', 'CartController@response');
Route::get('cart/substitutions/{row}/{value}', 'CartController@substitutions');
Route::get('cart/disallow-substitutions', 'CartController@disallow_substitutions');
Route::get('cart/refresh', 'CartController@refresh');
Route::get('cart/refresh-top', 'CartController@refresh_top');
Route::get('cart/refresh-checkout', 'CartController@refresh_checkout');
Route::get('cart/refresh-sidebar', 'CartController@refresh_sidebar');

Route::post('cart-item/update/{id}', 'CartItemController@update');

Route::get('checkout', 'CartController@checkout')->middleware('personal-info')->name('checkout');

Route::get('cart/content', 'CartController@content');
Route::get('/cart/delete/{id}', 'CartController@delete');
Route::get('cart/comments/{item}/{comment}', 'CartController@comments');
Route::post('cart/add-item', 'CartController@add_item');
Route::get('cart/update-qty/{id}/{qty}', 'CartController@update_qty');
Route::post('cart/payment', 'CartController@payment');
Route::post('cart/payment-do/{id}', 'CartController@payment_do');
Route::post('cart/restore', 'CartController@restore');
Route::post('cart/cartstore', 'CartController@cartstore');
Route::post('cart/set_delivery_time', 'CartController@set_delivery_time');
Route::get('cart/delivery_times', 'CartController@delivery_times');
Route::get('cart/delivery_zip/{zip_code}', 'CartController@delivery_zip');
Route::get('cart/delivery_eligible/{zip}', 'CartController@delivery_eligible');
Route::post('cart/delivery_tip', 'CartController@add_delivery_tip');
Route::get('cart/update_delivery_status/{id}/{status}', 'CartController@update_delivery_status');
Route::get('clear-cart', 'CartController@clear');
Route::resource('cart', 'CartController');

Route::get('envoy/send/{id}', 'EnvoyController@send');

Route::get('store-selector', 'StoresController@store_selector');
Route::post('store-select', 'StoresController@store_select');

Route::get('feedback', 'ShoppingController@feedback');
Route::post('feedback-form', 'ShoppingController@feedback_form');
Route::get('contact', 'ShoppingController@contact');
Route::post('contact-form', 'ShoppingController@contact_form');
Route::get('notes/{id}', 'ShoppingController@notes')->name('add-note');
Route::post('notes-form/{id}', 'ShoppingController@notes_form');
Route::get('thankyou/{id}', 'ShoppingController@thankyou');

Route::get('favorites/add/{upc}', 'FavoritesController@add');
Route::get('favorites/{upc}', 'FavoritesController@toggle');

Route::group(['prefix' => 'shopping'], function () {
    Route::get('category/{id}', 'ShoppingController@category');
    Route::get('product/{id}', 'ShoppingController@product');
    Route::get('search', 'ShoppingController@search');
    Route::get('search_aws', 'ShoppingController@search_aws');
    Route::post('autocomplete', 'ShoppingController@autocomplete');
    Route::get('reset-location', 'ShoppingController@reset_location');
    Route::get('pickup-times/{date}/{location}', 'ShoppingController@pickup_times');
    Route::get('delivery-times/{date}/{location}', 'ShoppingController@delivery_times');
    Route::post('pickup-settings', 'ShoppingController@pickup_settings');
    Route::get('pickup-reset', 'ShoppingController@pickup_reset');
    Route::get('delivery-reset', 'ShoppingController@delivery_reset');
});

Route::group(['prefix' => 'admin', 'middleware' => 'approved'], function () {
    Route::get('', 'AdminController@index')->name('admin');
    Route::get('index-data', 'AdminController@index_data');
    Route::get('login-using-id/{id}', 'AdminController@login_using_id');
    Route::get('order/summary/{images}/{id}', 'OrdersController@summary');
    Route::get('order/packaging/{id}', 'OrdersController@packaging');
    Route::get('order/report/{id}/{store}', 'OrdersController@report');
    Route::get('order/out-of-stock/{id}/{store}/{user}', 'OrdersController@out_of_stock');
    Route::get('order/call-notification/{id}', 'OrdersController@call_notification');
    Route::get('order/text-notification/{id}', 'OrdersController@text_notification');
    Route::get('order/over-total/{id}', 'OrdersController@over_total');
    Route::get('order/guest-check/{id}', 'OrdersController@guest_check');
    Route::get('order/excel-full-report', 'AdminController@excel_full_report');
    Route::post('order/signature/{id}', 'OrdersController@save_signature');
    Route::post('order/picked/{id}', 'OrdersController@picked');
    Route::post('order/picker-comment/{id}/{comment}', 'OrdersController@picker_comment');
    Route::resource('order', 'OrdersController');
    Route::get('improvement-request', 'AdminController@improvement_request');
    Route::post('improvement-request-form', 'AdminController@improvement_request_form');
    Route::get('reminder', 'OrdersController@reminder');
    Route::get('top-sellers-report', 'AdminController@top_sellers_report');
    Route::get('top-sellers-report-excel', 'AdminController@top_sellers_report_excel');
    Route::get('thanx', 'AdminController@thanx');
    Route::get('top-customers', 'AdminController@top_online_shoppers');
    Route::post('customer-orders', 'AdminController@customer_orders');

    Route::resource('reports', 'ReportsController');
});

Route::group(['prefix' => 'account'], function () {
    Route::get('my-account', 'AccountsController@my_account');
    Route::get('order-details/{order}', 'AccountsController@order_details');
    Route::get('previous-orders', 'AccountsController@previous_orders');
    Route::get('reorder-items/{order}', 'AccountsController@reorder_items');
    Route::get('favorites', 'AccountsController@favorites');
    Route::get('change-password', 'AccountsController@change_password');
    Route::post('update-pass', 'AccountsController@update_pass');
    Route::get('personal-info', 'AccountsController@personal_info')->name('personal-info');
    Route::post('update-user', 'AccountsController@update_user');
    Route::get('loyalty', 'AccountsController@loyalty_index');
    Route::post('loyalty-login', 'AccountsController@loyalty');
});

Route::get('terms', 'ShoppingController@terms');

Route::get('total-top', function () {
    return \Gloudemans\Shoppingcart\Facades\Cart::total();
});

Route::get('checkout-tax', function () {
    $x = (\Gloudemans\Shoppingcart\Facades\Cart::total() - \Gloudemans\Shoppingcart\Facades\Cart::subtotal());

    return number_format($x, 2);
});

Route::group(['prefix' => 'stripe'], function(){
    Route::post('create-payment-intent', 'StripeController@create_payment_intent')->name('create-payment-intent');
});

Route::group(['middleware' => 'guest'], function(){

    Route::get('/sign-in/facebook', 'Auth\LoginController@facebook');
    Route::get('/sign-in/facebook/redirect', 'Auth\LoginController@facebook_redirect');

});

Route::resource('custom-item', 'CustomItemController');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = [
        'upc',
        'name',
        'price',
        'qty',
        'allow_substitutions',
        'comments',
        'dept_code',
        'image',
        'picked',
        'picked_qty',
        'out_of_stock',
        'substitute',
        'scale_flag',
        'custom_item'
    ];

    public function getAllowSubstitutionsAttribute($value)
    {
        $subs = 'No';

        if ($value == 1) {
            $subs = 'Yes';
        }

        return $subs;
    }

    public function order()
    {
        return $this->belongsTo(\App\Order::class);
    }

    /**
     *  Subtotal.
     */
    public function getSubtotalAttribute()
    {
        return $this->attributes['picked_qty'] * $this->attributes['price'];
    }

    /**
     *  Is Picked Attribute.
     */
    public function getIsPickedAttribute()
    {
        if ($this->out_of_stock) {
            return true;
        }

        if ($this->picked_qty >= $this->qty) {
            return true;
        }

        return false;
    }

    public function setCustomItemAttribute($value)
    {
        if($value !== null)
        {
            return $value;
        }

        return 0;
    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Order extends Model
{
    protected $fillable = [

        'pickup_date',
        'pickup_time',
        'name',
        'phone',
        'email',
        'comments',
        'payment_method',
        'total_order',
        'final_amount',
        'subtotal',
        'total',
        'tax',
        'pos_id',
        'pos_received',
        'status',
        'store',
        'paypal_token',
        'paypal_payer_id',
        'cancel_reason',
        'is_complex',
        'complex',
        'substitutions_preference',
        'billing_address',
        'zip_code',
        'tax_exempt',
        'tax_number',
        'completion_date',
        'shopper',
        'shopper_start_time',
        'shopper_end_time',
        'delivery_tip',
        'delivery_id',
        'delivery_address',
        'delivery_city',
        'delivery_zip_code',
        'delivery_first_name',
        'delivery_last_name',
        'delivery_phone',
        'delivery_instructions',
        'delivery_time',
        'score',
        'score_comments',

    ];

    /**
     *  Substitutions Preference Mutator.
     */
    public function getSubstitutionsPreferenceAttribute($value)
    {
        $subs = [
            null => 'Contact Me',
            'contact_me' => 'Contact Me',
            'use_best_judgement' => 'Use Best Judgement',
            'do_not_substitute' => 'Do Not Substitute',
        ];

        return $subs[$value];
    }

    /**
     *  Is active attribute.
     */
    public function getIsActiveAttribute()
    {
        if ($this->status == 'PLACED' || $this->status == 'In Progress' || $this->status == 'POS') {
            return true;
        }

        return false;
    }

    /**
     *  Label Attribute
     */

    public function getLabelAttribute()
    {
        $vars = [
            'PAYMENT' => 'label-default',
            'PLACED' => 'label-danger',
            'In Progress' => 'label-warning',
            'POS' => 'label-info',
            'COMPLETED' => 'label-success',
            'DELIVERED' => 'label-info',
            'CANCELLED' => 'label-info'
        ];

        return $vars[$this->attributes['status']] . ' text-uppercase';
    }

    /**
     *  Is a Custom Items Order
     */

    public function getIsCustomItemsOrderAttribute()
    {
        if( $this->items()->whereCustomItem(1)->count() == $this->items()->count() )
        {
            return true;
        }

        return false;
    }

    /**
     *  First Name Attribute.
     */

    public function getFirstNameAttribute()
    {
        return explode(' ', $this->attributes['name'])[0];
    }

    /**
     *  Items.
     */
    public function items()
    {
        return $this->hasMany(\App\Item::class);
    }

    /**
     *  Notes.
     */
    public function notes()
    {
        return $this->hasMany(\App\Note::class);
    }

    /**
     *  User Orders.
     */
    public function scopeUser()
    {
        return $this->where('email', Auth::user()->email);
    }

    /**
     * Customer Relationship
     */

    public function customer()
    {
        return $this->belongsTo(User::class, 'user_id', 'id'    );
    }
}

resources/views/picking/picking-items.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <p class="lead text-center">
            Picking Order # {{ $order->id }}<br />{{ number_format(($order->items->filter(function($item){ return $item->is_picked; })->count() / $order->items->count()) * 100, 0) }}%
        </p>

        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                <form action="{{ action('PickingController@picked', $order->id) }}" method="post">
                    @csrf
                    <div class="form-group">
                        <div class="input-group">
                            <input type="number" class="form-control text-center" name="upc" id="scan" placeholder="Scan Item" required >
                            <span class="input-group-btn">
                    <button class="btn btn-danger btn-block">
                        Add
                    </button>
                    </span>
                        </div>
                    </div>

                </form>

                @if( ($order->items->filter(function($item){ return $item->is_picked || $item->out_of_stock == 1; })->count() / $order->items->count()) >= 1 )

                    @if( !$order->is_custom_items_order )

                        @if( $order->comments !== null || $order->comments !== '' )
                        <div class="form-group">
                            <button class="btn-lg btn-success btn-block" data-toggle="modal" data-target="#pos-confirm">
                                Send to POS
                            </button>
                            <div class="modal fade" tabindex="-1" role="dialog" id="pos-confirm">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title">Did you read the customer comments?</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p class="lead">{{ $order->comments }}</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">No. Go Back.</button>
                                            <a href="{{ action('PosController@add_order', [$order->id, 2]) }}" class="btn btn-primary">Yes. Send to POS.</a>
                                        </div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog -->
                            </div><!-- /.modal -->
                        </div>
                        @else
                        <div class="form-group">
                            <a class="btn-lg btn-success btn-block text-center" href="{{ action('PosController@add_order', [$order->id, 2]) }}">
                                Send to POS
                            </a>
                        </div>
                        @endif


                    @else
                    <div class="form-group">
                        <button class="btn btn-danger btn-block">
                            <i class="fa fa-exclamation-triangle"></i> This order contains only custom orders and can't be sent to the POS.
                        </button>
                    </div>
                    @endif

                @endif

                <div class="form-group">
                    <select id="dept-select" class="form-control">
                        <option value="">All items</option>
                        @foreach($order->items->groupBy('dept_code') as $dept)
                            <option value="{{ $dept[0]->dept_code }}">{{ DB::table('store_departments')->where('store_department', $dept[0]->dept_code)->first()->description }}</option>
                        @endforeach
                    </select>
                </div>

                @if($order->comments !== null && $order->comments !== '')
                    <div class="alert alert-danger">
                        {{ $order->comments }}
                    </div>
                @endif

            </div>
        </div>

        @foreach( $order->items->sortBy('is_picked') as $item )
        <div class="row">
            <div class="col col-sm-4 col-sm-offset-4">
                <div class="panel @if( $item->is_picked ) panel-success @else panel-danger @endif item item-{{ $item->dept_code }}">
                    <div class="panel-body">
                        @if( $item->comments !== null && $item->comments !== '' )
                            <div class="alert alert-danger">
                                <i class="fa fa-exclamation-triangle"></i> {{ $item->comments }}
                            </div>
                        @endif
                        @if( $item->custom_item )
                        <div class="alert alert-danger">
                            <i class="fa fa-exclamation-triangle"></i> You will need to ring this item at the POS level.
                        </div>
                        @endif
                        <div class="col-xs-4">
                            <img
                                    src="/img/transparent.png"
                                    style="background:url({!! $item->image !!}); background-size: contain; background-repeat: no-repeat; background-position: center top;"
                                    alt=""
                                    class="img-responsive"
                            >
                            <div style="font-size: 9px;" class="text-center">
                                {{ $item->upc }}
                            </div>
                            @if( !$item->is_picked && !$item->out_of_stock )
                                <form action="{{ route('is-out-of-stock', $item->id) }}" onsubmit="return confirm('Is the item {{ str_replace("'", "`", $item->name) }} out of stock?')" method="post">
                                    @csrf
                                    <button class="btn-xs btn-default btn-block" style="font-size: 9px;">Out of Stock</button>
                                </form>
                            @endif
                        </div>
                        <div class="col-xs-8">
                            <p class="text-right">
                                <b>{{ $item->name }}</b>
                                <br />{{ $item->price }}
                            </p>
                            <p class="text-right">
                        <span class="row">
                            <span class="col-xs-6">
                                Ordered Qty: {{ $item->qty }}
                            </span>
                            <span class="col-xs-6">
                                <a onclick="$('#scan').focus()" href="#" data-toggle="modal" data-target="#picking-modal-{{ $item->id }}">Picked Qty: {{ $item->picked_qty }}</a>
                            </span>
                        </span>
                            </p>

                            <!-- Modal -->
                            <div class="modal fade" id="picking-modal-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        @if( $item->comments !== null && $item->comments !== '' )
                                        <div class="alert alert-danger">
                                            <p>
                                                <b><i class="fa fa-exclamation-triangle"></i> A note has been added to this item:</b><br />
                                                {{ $item->comments }}
                                            </p>
                                        </div>
                                        @endif
                                        <form action="{{ route('item.update', $item->id) }}" method="post">
                                            @csrf
                                            @method('PATCH')
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title text-center" id="myModalLabel">Enter picked Qty</h4>
                                            </div>
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <label>{{ $item->name }}</label>
                                                    <input type="number" name="picked_qty" class="form-control input-lg text-center" placeholder="1.0" step="0.01" min="0" value="{{ $item->qty }}">
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        @if( $item->allow_substitutions == 'Yes' )
                        Substitutions allowed.
                        @else
                        Substitutions NOT allowed.
                        @endif
                    </div>
                </div>
            </div>
        </div>
        @endforeach

        <p class="text-center">
            <i>{{ $order->items->count() }} items found.</i>
        </p>

    </div>

    <div class="container">
        <div class="alert alert-info">
            If an item is out of stock, please find an appropriate substitution suggestion for the guest. This would preferably be <b>same product, different brand</b>. However, please use your best judgement (Pay attention to gluten free and organic items). If the item is continually out of stock, please notate in your admin page by <b>reporting an item</b> that we do not carry.
        </div>
    </div>

    @endsection

@section('js')

    <script>
        $(document).ready(function(){
            $('#scan').focus();
        });

        $('#dept-select').change(function(){
            if( $(this).val() === "" )
            {
                $('.item').show();
            }else{
                var dept = $(this).val();
                $('.item').hide();
                $('.item-' + dept).show();
            }
        });
    </script>

    @endsection

resources/views/picking/price-check.blade.php
@extends('layouts.admin')

@section('content')
    
    <div class="container-fluid">
        <p class="lead text-center">Price Check</p>
        <form action="{{ route('price-check') }}">
            <div class="form-group">
                <input type="text" class="form-control input-lg text-center" name="upc" placeholder="Scan Item" id="scan">
            </div>
        </form>

        @if( $product != null )
        <p class="text-center">
            <b>{{ $product->product_description }}</b>
        </p>
        <p class="lead text-center">
            {{ $product->ip_unit_price }}
        </p>
        <p class="text-center">
            <span class="badge badge-primary">{{ $product->descriptive_size }}</span>
        </p>
        @else
        <div class="alert alert-danger text-center">
            Product Not Found
        </div>
        @endif
    </div>
    
    @endsection

@section('js')

    <script>
        $(document).ready(function(){
            $('#scan').focus();
        });
    </script>

@endsection

resources/views/picking/substitute.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <p class="lead text-center">Item Substitution</p>

        @if( $order->items->filter(function($item){ return $item->is_picked !== true && $item->out_of_stock !== 1; })->count() > 0 )
        <p class="lead text-center">
            From the list below, please select the item you will substitute with
            <br /><b>{{ $product->name }}</b>:
        </p>
        <ul class="list-group">
            @foreach( $order->items->filter(function($item){ return ($item->picked !== 1) && ($item->out_of_stock !== 1); }) as $item )
            <li class="list-group-item text-center">
                <a onclick="return confirm('Are you sure you want to substitute ' + '{{ $item->name }}' + ' with ' + '{{ $product->name }}' + '?')" href="{{ route('add-substitute', [$order->id, $item->id, $product->upc]) }}"  >
                    {{ $item->name }}
                </a>
            </li>
            @endforeach
        </ul>
        <p class="lead text-center">
            Or
        </p>
        @else
        <p class="lead text-center">
            There are no items to substitute.
        </p>
        @endif

        <p class="text-center">
            <a href="{{ route('add-item', [$order->id, $product->upc]) }}" class="btn-lg btn-success">
                Add item to the order
            </a>
        </p>

    </div>

    @endsection